In [ ]:
#   Created by Elshad Karimov on 05/04/2020.
#   Copyright © 2020 AppMillers. All rights reserved.

import numpy as np

In [2]:
twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [12]:
newTwoDArray = np.insert(twoDArray, 1, [[1,2,3,4]], axis=0)
print(newTwoDArray)

[[11 15 10  6]
 [ 1  2  3  4]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [13]:
print(len(twoDArray))

4


In [14]:
newTwoDArray = np.append(twoDArray, [[1,2,3,4]], axis=0)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]


In [15]:
print(len(newTwoDArray))

5


In [16]:
print(len(newTwoDArray[0]))

4


In [ ]:
def accessElements(array, rowIndex, colIndex):
    if rowIndex >= len(array) or colIndex >= len(array[0]):
        print('Incorrect Index')
    else:
        print(array[rowIndex][colIndex])

In [21]:
accessElements(newTwoDArray, 3, 1)

18


In [22]:
def traverseTDArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])

In [23]:
traverseTDArray(twoDArray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [24]:
def searchTDArray(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'The value is located index '+str(i)+" "+str(j)
    return 'The element no found'

In [ ]:
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [ ]:
print(searchTDArray(twoDArray, 11))

The value is located index 0 0


In [34]:
newTDArray = np.delete(twoDArray, 1, axis=0)
print(newTDArray)

[[11 15 10  6]
 [12 17 12  8]
 [15 18 14  9]]


In [ ]:
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
